twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        company: 'RIMED PEYI YA'
        project_dir: '%kernel.project_dir%' # 

when@test:
    twig:
        strict_variables: true